#!/usr/bin/env python3
"""
Build `patterns.js` — the behavioural and forensic pattern data for patterns.html.

Everything here comes from the REAL decoded log of device 862636058411560.
Nothing is simulated. Where the 0.5% corruption biases a figure, the bias is
carried through into the output so the page can label it rather than hide it.

Usage:
    python build_patterns.py
"""

import collections
import datetime as dt
import json
import os
import statistics as stats
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MINE = os.path.dirname(HERE)
PROJECT = os.path.dirname(MINE)
sys.path.insert(0, MINE)

from decode_log import parse, reject_reason, FLAG_GPS_FIX  # noqa: E402
from build_data import _find  # noqa: E402

LOG = _find("*_LOG*.TXT", os.path.join(PROJECT, "Not mine"), PROJECT, MINE)
OUT = os.path.join(HERE, "patterns.js")

IDLE_MAX = 900          # below this and running = idle
BIN = 100               # rpm histogram bin width
BUCKET_S = 1800         # 30-minute buckets


def main():
    records, _ = parse(LOG)
    idx = [i for i, r in enumerate(records) if reject_reason(r) is None]
    V = sorted((records[i] for i in idx), key=lambda r: (r[0], r[1]))
    if not V:
        raise SystemExit("no valid records")

    # ---- 1. RPM distribution -------------------------------------------
    hist = collections.Counter(r[2] // BIN * BIN for r in V)
    rpm_hist = [
        {"bin": b, "label": f"{b}–{b + BIN - 1}", "n": hist[b],
         "zone": "idle" if b + BIN - 1 < IDLE_MAX else "working"}
        for b in range(min(hist), max(hist) + BIN, BIN)
    ]

    # ---- 2. Shift timeline ---------------------------------------------
    timeline = [{"t": r[0], "rpm": r[2]} for r in V]

    # ---- 3. Idle vs working per 30 min ---------------------------------
    t0 = V[0][0]
    buckets = collections.defaultdict(lambda: {"idle": 0, "working": 0})
    for r in V:
        k = (r[0] - t0) // BUCKET_S
        buckets[k]["idle" if 0 < r[2] < IDLE_MAX else "working"] += 1
    span = [
        {"t": t0 + k * BUCKET_S, "idle": buckets[k]["idle"],
         "working": buckets[k]["working"],
         "n": buckets[k]["idle"] + buckets[k]["working"]}
        for k in sorted(buckets)
    ]

    # ---- 4. Forensic: how far apart do valid records fall? --------------
    gaps = [idx[i + 1] - idx[i] for i in range(len(idx) - 1)]
    edges = [(1, 1), (2, 5), (6, 10), (11, 25), (26, 50), (51, 100),
             (101, 500), (501, 2000), (2001, 10 ** 9)]
    gap_hist = []
    for lo, hi in edges:
        n = sum(1 for g in gaps if lo <= g <= hi)
        gap_hist.append({
            "label": f"{lo}" if lo == hi else (f"{lo}+" if hi > 10 ** 8 else f"{lo}–{hi}"),
            "n": n})
    runs, cur = [], 1
    for i in range(1, len(idx)):
        if idx[i] == idx[i - 1] + 1:
            cur += 1
        else:
            runs.append(cur); cur = 1
    runs.append(cur)

    # ---- 5. Dead-signal evidence ---------------------------------------
    distinct = {
        "coolant": len(set(r[5] for r in V)),
        "rpm": len(set(r[2] for r in V)),
        "fuel": len(set(r[4] for r in V)),
        "torque": len(set(r[3] for r in V)),
    }
    coolant = [{"v": v, "n": n}
               for v, n in collections.Counter(r[5] for r in V).most_common()]

    idle_n = sum(1 for r in V if 0 < r[2] < IDLE_MAX)
    work_n = sum(1 for r in V if r[2] >= IDLE_MAX)

    payload = {
        "generated": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "device": "862636058411560",
        "asset": "EX-340D-01 · CAT 340 D",
        "framed": len(records),
        "valid": len(V),
        "validPct": round(100.0 * len(V) / len(records), 2),
        "shiftStart": V[0][0],
        "shiftEnd": V[-1][0],
        "idleN": idle_n,
        "workingN": work_n,
        "idlePct": round(100.0 * idle_n / (idle_n + work_n), 1),
        "idleThreshold": IDLE_MAX,
        "rpmHist": rpm_hist,
        "timeline": timeline,
        "span": span,
        "gapHist": gap_hist,
        "gapMedian": stats.median(gaps),
        "gapMean": round(stats.mean(gaps), 1),
        "gapMax": max(gaps),
        "runSingles": sum(1 for r in runs if r == 1),
        "runTotal": len(runs),
        "distinct": distinct,
        "coolant": coolant,
        "torqueIdle": stats.median([r[3] for r in V if 0 < r[2] < IDLE_MAX]),
        "torqueWorking": stats.median([r[3] for r in V if r[2] >= IDLE_MAX]),
        "gpsFixPct": round(100.0 * sum(1 for r in V if r[8] & FLAG_GPS_FIX) / len(V), 1),
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// Generated by build_patterns.py — real data, do not edit.\n")
        fh.write("window.PATTERNS = ")
        json.dump(payload, fh, separators=(",", ":"))
        fh.write(";\n")

    print(f"valid        : {len(V):,} of {len(records):,} ({payload['validPct']}%)")
    print(f"idle share   : {payload['idlePct']}%  ({idle_n} idle / {work_n} working)")
    print(f"rpm bins     : {len(rpm_hist)}   30-min buckets: {len(span)}")
    print(f"gaps         : median={payload['gapMedian']} mean={payload['gapMean']} "
          f"max={payload['gapMax']:,}")
    print(f"runs         : {payload['runSingles']} singletons of {payload['runTotal']}")
    print(f"distinct     : {distinct}")
    print(f"wrote        : {OUT} ({os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    main()
